version: '3.4'

services:
  carbooking:
    environment:
        ConnectionStrings__DefaultConnection: Server=mssql,1433;Database=CarBookingDatabase;User Id=sa;Password=!Password1;
    image: alexikon/carbookingapi
    build:
        context: .
        dockerfile: CarBooking/Dockerfile
    ports:
        - 5000:5000
    depends_on:
        - mssql
  mssql:
    image: 'mcr.microsoft.com/mssql/server'
    environment:
        SA_PASSWORD: '!Password1'
        ACCEPT_EULA: 'Y'